// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'Firebase non configuré pour iOS.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'Firebase non configuré pour macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Firebase non configuré pour Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Firebase non configuré pour Linux.',
        );
      default:
        throw UnsupportedError(
          'Plateforme non supportée.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtekrZwt0NfFvsRmQpaTvtf244Y-hbhyM',
    appId: '1:9575574160:web:b84ddf2254c2d4a95e4615',
    messagingSenderId: '9575574160',
    projectId: 'ilyasapp-4762c',
    authDomain: 'ilyasapp-4762c.firebaseapp.com',
    databaseURL: 'https://ilyasapp-4762c-default-rtdb.firebaseio.com',
    storageBucket: 'ilyasapp-4762c.firebasestorage.app',
  );

  // 🌐 WEB

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCGbbRKjdyRPajTfcCrkOpYm_etinNJ6Y',
    appId: '1:9575574160:android:b11ae77d8f8fd2c55e4615',
    messagingSenderId: '9575574160',
    projectId: 'ilyasapp-4762c',
    databaseURL: 'https://ilyasapp-4762c-default-rtdb.firebaseio.com',
    storageBucket: 'ilyasapp-4762c.firebasestorage.app',
  );

  // 🤖 ANDROID
}